import telebot
from telebot import types

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

token = "5416667430:AAFIkaLXaxd2nNaW7S4VUtTyjBIFUVNipS0"
bot = telebot.TeleBot(token)

from selenium import webdriver
driver = webdriver.Chrome(executable_path="c:\chromedriver.exe")




class TestAuth():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_auth(self):
        self.driver.get("https://pro.firpo.ru/netcat/")
        self.driver.set_window_size(945, 1020)
        time.sleep(2)
        self.driver.find_element(By.ID, "AUTH_USER").click()
        self.driver.find_element(By.ID, "AUTH_USER").send_keys("modpro@firpo.ru")
        time.sleep(2)
        self.driver.find_element(By.NAME, "AUTH_PW").click()
        self.driver.find_element(By.NAME, "AUTH_PW").send_keys("wqd98378gcsckj")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > .nc-btn").click()


class TestExit():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_exit(self):
        self.driver.get("https://pro.firpo.ru/netcat/admin/?attempt=1#index")
        self.driver.set_window_size(945, 1020)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".nc-tray > .nc--dropdown > a").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".nc-tray > .nc--dropdown > a")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(2)
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Выход").click()


class TestUp():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_up(self):
        self.driver.get("https://pro.firpo.ru/netcat/admin/?attempt=1#index")
        self.driver.set_window_size(945, 1020)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT,
                                 "7. Всероссийское чемпионатное движение по профессиональному мастерству").click()
        self.driver.switch_to.default_content()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#mainViewTab_edit > span").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#mainViewToolbar_edit > .button").click()
        self.driver.switch_to.frame(1)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".nc_admin_settings_info_checked label").click()
        self.driver.switch_to.default_content()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".save").click()


class TestDown():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_down(self):
        self.driver.get("https://pro.firpo.ru/netcat/admin/?attempt=1#index")
        self.driver.set_window_size(945, 1020)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT,
                                 "7. Всероссийское чемпионатное движение по профессиональному мастерству").click()
        self.driver.switch_to.default_content()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#mainViewTab_edit > span").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#mainViewToolbar_edit > .button").click()
        self.driver.switch_to.frame(1)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".nc_admin_settings_info_checked label").click()
        self.driver.switch_to.default_content()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".save").click()




@bot.message_handler(commands=['start'])
def start(message):

    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    btn1 = types.KeyboardButton("👋 Hey")
    markup.add(btn1)
    bot.send_message(message.from_user.id, "👋 Привет! Я твой бот-помошник!", reply_markup=markup)

@bot.message_handler(content_types=['text'])
def get_text_messages(message):

    if message.text == '👋 Hey':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True) #создание новых кнопок
        btn1 = types.KeyboardButton('Auth')
        btn2 = types.KeyboardButton('up')
        btn3 = types.KeyboardButton('down')
        btn4 = types.KeyboardButton('exit')
        markup.add(btn1, btn2, btn3, btn4)
        bot.send_message(message.from_user.id, 'Что нужно❓', reply_markup=markup) #ответ бота


    elif message.text == 'Auth':
        #driver.get("https://pro.firpo.ru/netcat/")
        #TestAuth()

        #driver = webdriver.Chrome()
        #vars = {}


        #driver.quit()


        driver.get("https://pro.firpo.ru/netcat/")
        driver.set_window_size(945, 1020)
        time.sleep(2)
        driver.find_element(By.ID, "AUTH_USER").click()
        driver.find_element(By.ID, "AUTH_USER").send_keys("modpro@firpo.ru")
        time.sleep(2)
        driver.find_element(By.NAME, "AUTH_PW").click()
        driver.find_element(By.NAME, "AUTH_PW").send_keys("wqd98378gcsckj")
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > .nc-btn").click()
        bot.send_message(message.from_user.id,
                         'Авторизован!', parse_mode='Markdown')

    elif message.text == 'up':
        driver.get("https://pro.firpo.ru/netcat/admin/?attempt=1#index")
        driver.set_window_size(945, 1020)
        driver.switch_to.frame(0)
        driver.find_element(By.LINK_TEXT,
                                 "7. Всероссийское чемпионатное движение по профессиональному мастерству").click()
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, "#mainViewTab_edit > span").click()
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, "#mainViewToolbar_edit > .button").click()
        driver.switch_to.frame(1)
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".nc_admin_settings_info_checked label").click()
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".save").click()
        bot.send_message(message.from_user.id, 'Поднят ' + '[ссылке](https://pro.firpo.ru/)', parse_mode='Markdown')

    elif message.text == 'down':
        driver.get("https://pro.firpo.ru/netcat/admin/?attempt=1#index")
        driver.set_window_size(945, 1020)
        driver.switch_to.frame(0)
        driver.find_element(By.LINK_TEXT,
                                 "7. Всероссийское чемпионатное движение по профессиональному мастерству").click()
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, "#mainViewTab_edit > span").click()
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, "#mainViewToolbar_edit > .button").click()
        driver.switch_to.frame(1)
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".nc_admin_settings_info_checked label").click()
        driver.switch_to.default_content()
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".save").click()
        bot.send_message(message.from_user.id, 'Вырублен ' + '[ссылке](https://pro.firpo.ru/)', parse_mode='Markdown')

    elif message.text == 'exit':
        driver.get("https://pro.firpo.ru/netcat/admin/?attempt=1#index")
        driver.set_window_size(945, 1020)
        time.sleep(2)
        driver.find_element(By.CSS_SELECTOR, ".nc-tray > .nc--dropdown > a").click()
        element = driver.find_element(By.CSS_SELECTOR, ".nc-tray > .nc--dropdown > a")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        time.sleep(2)
        element = driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        time.sleep(2)
        driver.find_element(By.LINK_TEXT, "Выход").click()
        bot.send_message(message.from_user.id, 'Выход', parse_mode='Markdown')


bot.polling(none_stop=True, interval=0) #обязательная для работы бота часть